server:
  port: 8081

#自定义配置
my:
  #心情语录
  mood:
    today: 周五
    content: 努力工作
    author: "小程序员"
  #功能开关
  feature:
    helloSwitch: false
    closeMsg: "该接口正在维护，10分钟后再来吧！"

zmy:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c401991c596b912056
      accountToken: 4dd42e79c99b4b45a8c8e3774e77e0cf
      appId: 2c94811c9860a9c401991c596d1b205d
      templateId: 1


