server:
  port: 8081


team:
  leader: "zmy"
  phone: "13218583758"
  age: 3
  createDate: "2019-09-01"

spring:
  servlet:
    multipart:
      max-file-size: 10MB  # 单个上传文件大小限定为10M，默认值为1M
      max-request-size: 100MB  # 单次上传文件大小限定为100M，默认值为10M
